SuffolkLITLab/docassemble-AssemblyLine

- docassemble/AssemblyLine/data/questions/ql_baseline.yml
https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/issues/121#issuecomment-769230682 has most of the background for this change. 
We should consider that this will **force the user to give their address**, even if the form doesn't need it, which seems iffy. Some other (more complicated) ways of fixing this missing address issue:
* have a different address ask screen that doesn't mark the address as required, but instead indicates that entering their address will help them later in the interview but isn't necessary for the form itself (do courts always need the address of the user? We might eventually want it when we gather interview stats)
* Add an intermediate `id: choose a court (no address given)` screen that looks like `id:choose a court (no matching courts found)`, but …
> Ask address of the user to help find the court

- docassemble/AssemblyLine/data/questions/ql_baseline.yml
Partially closes #18, which will be fully closed when the BBO number question is merged in ALMassachusetts.
If ALMassachusetts isn't included in an interview, this ask for a generic attorney ID number, with no validation.
> Added generic attorney ID question

- docassemble/AssemblyLine/data/questions/al_question_test.yml
- docassemble/AssemblyLine/data/questions/al_visual.yml
Close #40. You can test with [al_question_test.yml](https://apps-dev.suffolklitlab.org/interview?i=docassemble.playground12ALSoughtVar%3Aal_question_test.yml#page1) for a simple variable name and with [a test I made](https://apps-dev.suffolklitlab.org/interview?i=docassemble.playground12ALSoughtVar%3Atest.yml#page1) for a more complex variable name. It doesn't matter much as the variable name gets encoded.
> Close #40, and invisible sought var data to the dev DOM

- docassemble/AssemblyLine/al_general.py
- docassemble/AssemblyLine/data/questions/al_question_test.yml
- docassemble/AssemblyLine/data/questions/ql_baseline.yml
Refactored the existing code a bit to also allow people to ask for `show if`'d code for business or people. Existing question structure was taken from the `other_parties` default question, but needed it for `users` as well for some changes in the [Civil docketing statement](https://github.com/SuffolkLITLab/docassemble-AppealsCivilDocketingStatement/issues/12).
> Name fields with business option

- docassemble/AssemblyLine/data/questions/ql_baseline.yml
Close #63. Here's one way that seemed to work for me, following the proposed method in #63.
> Close #63, support previous `courts` object

- docassemble/AssemblyLine/al_general.py
Fixes #30. 
Example usage:
```
(in docx)
{{users[0].signature_if_final(i) }}
```
> Add a conditional signature function to ALIndividual

- docassemble/AssemblyLine/data/questions/al_code.yml
Got the below issue when testing with appeals code on a local docker instance.
```
TypeError: can only concatenate str (not "NoneType") to str
In line:   log("Court email is " + court_email)
```
This _should_ fix (still need to test though).
> If court_email is None, DA throws error

- docassemble/AssemblyLine/al_general.py
- docassemble/AssemblyLine/data/questions/ql_baseline.yml
Allows downstream interviews (specifically for the Civil Docketing Statement at the moment) to modify the labels shown for business vs person choices, and fixes a small bug (looking for `self.business_name_text` instead of `self.business_name_label`).
Tested on the Civil Docketing statement interview on dev, going to merge.
> New choice labels

- docassemble/AssemblyLine/data/questions/al_question_test.yml
- docassemble/AssemblyLine/data/static/al_audio.js
Fixes #68. For the page event, I would just call it `audio_test`, but I think this may be expanded. For example, it may also be used to test the 'escape' button, etc.
Test performed:
> Fix #68, custom audio elem gone when page help button is pressed

- docassemble/AssemblyLine/data/static/al_audio.js
Fixes #77.
Test performed:
I think 'restart' is better than showing 'play' again because it gives folks some indication that this is a different situation than when they just paused the audio. It's the same reason 'stop' makes the 'restart' icon appear.
> Fix #77, audio not resetting when done

- docassemble/AssemblyLine/data/questions/al_code.yml
A interview specific `package_title` can be set once https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/issues/113 is in the Weaver.
> Add default package title to AL, fixes #71

- docassemble/AssemblyLine/data/questions/ql_baseline.yml
fix #64 
Made the PeopleList questions for children, witnesses, and generic people more responsive.
Don't ask "How many" right away...first ask if there are any.
If the list uses target_number and the target is 1, don't ask about the "first", "second", etc. Instead ask for "name of the x"
Use noun_plural with x.object_name() so that nouns are currectly pluralized/made singular in the right contexts. "Do you have any other witnesses", "name of the first witness" etc.. These will work in English and Spanish but not other languages, so we may not be able to use these questions in all interviews. Still a useful default for English and Spanish interviews.
> Cleanup some awkward language with people lists - fix #64

- docassemble/AssemblyLine/al_document.py
- docassemble/AssemblyLine/data/questions/al_question_test.yml
Fix #98 
Added a new keyword parameter, `show_editable_checkbox` to the `send_button_html` method. When set to "False" the "Include editable copy" checkbox will not be displayed.
> Make the "include editable copy" checkbox optional

- docassemble/AssemblyLine/data/questions/al_settings.yml
This may affect some of the appeals court forms that have been migrated to the new AL code already; it will match most of the other forms that are getting automated though.
> Make "do not email to court" the default, instead of having emailing the default

- docassemble/AssemblyLine/data/questions/al_question_test.yml
- docassemble/AssemblyLine/data/static/aldocument.js
Fixes #120. This uses the first option suggested in #120.
> For now I went with option 1, though I'm not convinced it's the best option. It's just faster for me at this time in my life - for option 2 I need to look into what other attributes need to be set to disable the checkbox appropriately and accessibly.
> Fix #120, no email sent when editable checkbox not present

- docassemble/AssemblyLine/data/questions/al_visual.yml
Fix #58. Visually this could be improved, but I think it satisfies an MVP we can start getting feedback on. 
This is the last piece of #137 after #148 and #150 are merged. Recommend merging #148 first.
> Add a permalink and ability to share the interview progress/permalink via SMS or email (#58)

- .bumpversion.cfg
- CHANGELOG.md
- bumpversion.sh
Adds help text, dry-run capabilities, and lots more error checking to make sure things don't break, including:
* making sure all variables and required commands are defined
* fetching from remote and not allowing you to bump if you are behind the remote's version of your current branch.
* multiline changelog messages
If unexpected things happen, it can't rollback to how it was before running, but there are at least more tools to reduce that possibility.
Also, it won't make announcements to Teams on patches, just on minor or major releases. 
Fixes #122.
> Bumpversion reliant

- docassemble/AssemblyLine/al_document.py
- docassemble/AssemblyLine/data/questions/al_question_test.yml
- docassemble/AssemblyLine/data/static/aldocument.css
Closes #31 if accepted. It's one way to do it. I abstracted a little differently, so let me know if you want to chat about it.
Now that there was longer text to see in the title cell, the buttons arrangement wasn't looking as good, so I tweaked that css a bit.
[Also ran into a bit of weirdness where using `.enabled_documents()` triggered da to look for `al_user_bundle.there_is_another` or something like that. Not sure if it's a bug or if we're just not supposed to use that method.]
> Close #31, add zip row to table. Tweak and improve css.

- docassemble/AssemblyLine/al_document.py
- docassemble/AssemblyLine/data/questions/al_question_test.yml
Fixes #211 
This PR adds logic to store the enabled status of an ALDocument on the .cache attribute, which is reconsidered fresh on page loads (only when the attribute is needed on that page). That allows someone to dynamically change whether a document is included in the final download bundle or not by making changes on a review screen.
Side effect: you should not directly ask the user a question that sets the value of `my_doc.enabled`: instead, you can use an intermediate variable and set the value in a code block that references the intermediate variable. The code block will not be stale.
I also took the chance to do some small refactors in the al_question_test.yml file as I had to run it many times. I renamed some variables for clarity and removed some unused sections.
> Refresh `enabled` status of ALDocument objects once per page load

- docassemble/AssemblyLine/al_document.py
Close #249. Use `.as_pdf( refresh=False )` with a document. See no errors.
> Fix #249, key error when using `refresh=False` arg

- docassemble/AssemblyLine/al_courts.py
- docassemble/AssemblyLine/data/questions/test_alcourts.yml
Also does some transformation of the address if needed since it can come from user input. I can change that back if desired.
Having multiple pages this way ends up letting the test run faster. When we have a testing step for tapping the 'Back' button, we can get rid of some of these pages.
Close #252
> Close #252, alcourts tests MVP

- docassemble/AssemblyLine/al_document.py
Came across a bug in production today where, somehow, something was ending up as `None` in the HTML table. Full error is below. In general, I'm leaning towards making more things formatted strings, as I've seen the "`None` can't concatenate with `str`" error a few times now, and it's failing on trivial things like logs most of the time.
Tested in Playground, email still sends correctly and, to my knowledge, the tables all look right still.
```
Traceback (most recent call last):
File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args) …
```
> Safer html concats

- docassemble/AssemblyLine/al_general.py
- docassemble/AssemblyLine/data/questions/ql_baseline.yml
Fix #279 Fix #278 
Add an "unknown" option for gender (as forms in some provinces in Canada now provide)
Make all of the gender options work better as checkboxes in PDF forms. Currently, we provide a `x.gender_male` and `x.gender_female` attribute which is defined in a code block. That method doesn't work when you assemble a PDF that has `skip undefined` turned on, unless you explicitly trigger it in your interview order block. This PR makes the `gender_male` field into a method with the `@property` decorator, which is backwards compatible with the code block but works with `skip undefined`, and only requires that `gender` is defined explicitly.
I also added matching properties for each available gender choice for inclusive PDF forms.
A small test interview below shows that the new …
> Gender enhancements

- docassemble/AssemblyLine/al_document.py
- docassemble/AssemblyLine/data/questions/test_al_table_document.yml
Fix #294
Also adds a subclass ALUntransformedDocument that is more flexible to allow any DAFile without attempting to convert it to a PDF
> Add an ALDoc subclass to support exporting tables to XLSX

- docassemble/AssemblyLine/data/static/styles.css
Sorry, I was too quick. 
With this fix and https://github.com/SuffolkLITLab/docassemble-MassAccess/pull/1, you should see the effect like this:
> Issue #239.

- .gitignore
- docassemble/AssemblyLine/data/sources/test_aldocument.feature
We've had at least one incident of the tests not waiting quite long enough for the page to load all files. This will lengthen failing tests, but will also reduce false fails. Our group's conversations about this have led me to believe that the latter this approach the one we prefer.
I also adjusted the `.gitignore` to line up with the latest version of the testing framework. It's only an issue when running tests locally, but this will avoid accidentally checking in an unnecessary file under those circumstances.
> Add more time to custom max timeout

- docassemble/AssemblyLine/data/questions/ql_baseline.yml
Causes the question to be skipped, suprised that templates can have
continue button fields.
> Moved 'continue button field' from templ to ques

- docassemble/AssemblyLine/data/questions/al_settings.yml
- docassemble/AssemblyLine/data/questions/al_visual.yml
- docassemble/AssemblyLine/data/questions/feedback.yml
- docassemble/AssemblyLine/data/questions/ql_baseline.yml
Also replaced https://courtformsonline.org with AL_ORGANIZATION_HOMEPAGE
Decided to just use `CourtFormsOnline` everywhere to be consistent. Open to trying to edit things if we think that `Court Forms Online` (with spaces) is still useful.
Note also that prod doesn't have the variable "app hompage" in the config yet, so we're still depending on that default value. 
Fixes #346.
> Replace CourtFormsOnline w/ AL_ORGANIZATION_TITLE

- docassemble/AssemblyLine/data/questions/ql_baseline.yml
These two changes make the address field questions in ql_baseline just a little more robust. They [won't affect any existing repositories](https://github.com/search?p=1&q=org%3ASuffolkLITLab+mailing_address&type=Code).
No rush but might be nice to include with the next point release that has some more urgent fixes. Should be safe to merge with minimal review as it only adds new questions, doesn't replace any existing questions.
Here's a small test interview you can use:
```yaml
---
include:
- al_package.yml
---
objects:
- school_address: ALAddress
---
code: |
AL_DEFAULT_COUNTRY = "GB"
---
#mandatory: True
question: |
Mailing address
subquestion: |
${ users[0].mailing_address.block() }
---
#mandatory: True
question: |
${ defendants[0] }'s mailing address
subquestion: |
${ …
```
> Address question improvements

- docassemble/AssemblyLine/data/questions/al_document.yml
We were running into a problem where an interview that used `x.send_email()` without defining `users[0].name.first` would silently fail. It seems that an action needs to be idempotent as far as gathering information that the user inputs, but it can safely trigger code blocks that aren't defined yet.
Took the chance to also slightly clean up the template. We were using `metadata_title` which obscurely used a title defined in the "first" entry in the `interview_metadata` dictionary. That variable wasn't visibly used anywhere else and would be hard to relate to the actual interview someone is running. Also added the new `AL_ORGANIZATION_HOMEPAGE` to the bottom of the email template and made it possible to customize just the `document_label` on a per-bundle basis without having to create your …
> Safer idempotent email template

- .github/workflows/run_form_tests.yml
Based on https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-ignoring-branches-and-tags. May inform https://github.com/SuffolkLITLab/ALKiln/issues/380.
Not sure how we test this without just pushing to `main`.
> Try to prevent workflow run on tag pushes

- docassemble/AssemblyLine/al_document.py
- docassemble/AssemblyLine/data/sources/test_aldocument.feature
How would a developer handle this situation? Maybe we should add that to the documentation. Closes #264
> Return `None` when a bundle has no enabled documents.

- docassemble/AssemblyLine/data/sources/test_aldocument.feature
There's a kiln bug going on that's been letting these incomplete
tests pass. Because of the nature of the bug, the tests were,
strangely enough, doing what we wanted them to do anyway, but
this should prepare us for when that bug is fixed.
> Adds all needed vars to exhibits tests

- docassemble/AssemblyLine/al_document.py
- docassemble/AssemblyLine/data/questions/ql_baseline.yml
Fixes https://github.com/SuffolkLITLab/docassemble-MAHousingTRO/issues/12, which has been showing up in the live error reports for a while.
The issue was that it's using the [`review_all_sections` screen in `ql_baseline.yml`](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/9c99a360e385846ec7a259bf7c391fe505b950fa/docassemble/AssemblyLine/data/questions/ql_baseline.yml#L1237-L1258). Due to [a bad refactor on my part](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/commit/f694d8157d9d3e116bf841d394e32ab1404754dc), the `al_court_bundle.__str__()` method was being triggered, using DAList's implementation of it, which would run `._trigger_gather()`.
This should have been avoided because [we already set `gathered=True` and …
> Make review_all_sections handle partially gathered ALDocumentBundles

- docassemble/AssemblyLine/al_document.py
- docassemble/AssemblyLine/data/questions/test_aldocument.yml
- docassemble/AssemblyLine/data/sources/test_aldocument.feature
if `format="docx"` is specified, make the .zip file also have the DOCX formatted file. If `view` is set to `True`, the .zip will also contain a PDF with the DOCX.
Fix #190.
This will also allow someone to avoid Docassemble's PDF generation which can be slow when there are many files.
> Match ZIP contents to download list contents

- docassemble/AssemblyLine/al_document.py
Fixes #116
IMO it's been long enough for the debugging strings. They do clog up the logs when I'm trying to quickly look for other issues.
> No more debugging logging

- docassemble/AssemblyLine/data/questions/al_package.yml
- docassemble/AssemblyLine/data/questions/al_package_unstyled.yml
- docassemble/AssemblyLine/data/questions/assembly_line.yml
- docassemble/AssemblyLine/data/questions/assembly_line_unstyled.yml
Fix #38 
Don't think there are any other changes to the file layout that we have come up with in the last 12 months. This is an easy one that does help make the API for using AssemblyLine in your interview a little bit easier to follow.
> Add assembly_line.yml as an alias for al_package.yml

- .gitignore
- docassemble/AssemblyLine/al_courts.py
- docassemble/AssemblyLine/al_document.py
- docassemble/AssemblyLine/al_general.py
I've been slowing adding more python type annotations to AL, and checking them using mypy. It's caught a few poorly-defined behaviors, particularly in the python modules. It's hard to say if mypy would be useful for the interview YAMLs, but it's flexible enough to be useful for module files now.
Some of the examples of issues found by mypy:
* missing returns. Makes use add `Optional[ReturnVal]` where necessary
* making you have the same named arguments on subclass methods: otherwise, the defaults can't be expected to be the same (debatable if it applies to us, but good practice probably)
* different return types. The only one that I didn't correct was the fact that `ALExhibitDocument.al_list` says it returns a `List[DAFile]`, but it really returns a `List[ALExhibitDocument]`, and I'm not …
> Mypy changes

- docassemble/AssemblyLine/al_general.py
- docassemble/AssemblyLine/data/questions/ql_baseline.yml
ALIndividuals have a `previous_addresses` and `other_addresses` attribute but there was no reasonable question to provide a definition. This adds one so it's a little better than the generic object question for an ALAddress.
These questions are copied in from the 209A.
Test interview:
```yaml
---
include:
---
objects:
- mailman: ALIndividual
---
question: |
subquestion: |
Your current address is ${ users[0].address.on_one_line() }
Your mailing address is ${ users[0].mailing_address }
Your other addresses are ${ users[0].other_addresses }
Your previous addresses are ${ users[0].previous_addresses }
Addresses for your Mailman:
Mailman current address is ${ mailman.address.on_one_line() }
Mailman mailing address is ${ mailman.mailing_address }
Mailman …
```
> Add questions for `previous_addresses` and `other_addresses`

- docassemble/AssemblyLine/data/questions/feedback.yml
We have been running into the following error on prod for a while:
```
DAErrorMissingVariable: 
Interview has an error.  There was a reference to a variable 'AL_ORGANIZATION_TITLE' that could not be looked up in the question file (for language 'en') or in any of the files incorporated by reference into the question file.
The referer URL was http://suffolklitlab.org
```
But it's been impossible to find where it was happening from the email. I tried at one point opening and going through every single interview on court forms online, since the referer URL was suffolklitlab.org, but none of them failed on the landing page, which is what I would have expected from that referer.
Finally realized that the DA logs might have more information, and I was able to find that it's coming from this …
> Making sure that AL_ORGANIZATION_TITLE is defined

- docassemble/AssemblyLine/al_general.py
Fix #388 
Per request from @mnewsted, this method allows you to print the names in an ALPeopleList without shortening middle names to an initial.
Short test YAML:
```yaml
---
include:
---
question: |
${ children.full_names(and_string="or", comma_string="; ") }
```
> Add `full_names` method to ALPeopleList class

- docassemble/AssemblyLine/data/questions/ql_baseline.yml
Fixes bug in the existing ALExhibit questions where you are currently only prompted to add additional pages for the first exhibit.
> Allow someone to add multiple pages to the *second*+ exhibit document in ALExhibit model questions

- docassemble/AssemblyLine/al_courts.py
- docassemble/AssemblyLine/data/questions/al_saved_sessions.yml
- docassemble/AssemblyLine/language.py
Some of the instability of copying session data into a new interview comes from file permissions. This removes file objects from saved sessions to avoid those complications.
A review of this PR can just be an "it still runs" review as this is still a developer-oriented feature. I'm going to continue to make additional small PRs to refine different aspects of the feature and eventually make it usable by members of the public.
> Dont snapshot files and filelike objects when saving a session

- .github/workflows/unittests.yml
- docassemble/AssemblyLine/al_document.py
- docassemble/AssemblyLine/requirements.txt
- docassemble/AssemblyLine/test_al_document.py
- setup.py
Fix #426
Don't assume that if a document isn't a DOCX there is a PDF version of it--instead, check and return the closest thing to an "editable" document that we can for the given file.
Also added a semantically equivalent as_docx_list() method that mirrors as_pdf_list and will call the generally safe as_docx() method for each file in the bundle instead of directly referencing the .docx or .pdf attribute. Adding this as a separate method in case someone was relying on the behavior of as_editable_list.
> Add additional safety to as_editable_list() method of ALDocumentBundle

- docassemble/AssemblyLine/al_document.py
- docassemble/AssemblyLine/data/questions/ql_baseline.yml
- docassemble/AssemblyLine/data/questions/test_aldocument.yml
Fix #427 
Limitations:
- The ALDocumentUpload can only contain one DAFile
> Add ALDocumentUpload class to allow adding a simple uploaded file to an ALDocumentBundle

- docassemble/AssemblyLine/al_document.py
Fix #404. 
This class was designed to meet a need that hasn't surfaced yet. It isn't referenced anywhere in [any public github repository](https://github.com/search?q=ALDocumentBundleDict&type=code) other than our documentation.
Instead of the ALDocumentBundleDict class, someone can just add multiple ALDocumentBundle variables or create their own list or dictionary to display them to the user--the class-specific features are redundant because the ALDocumentBundle can already be nested.
It also has never been tested. Removing it so people don't accidentally use it.
> Remove the unused ALDocumentBundleDict class

- docassemble/AssemblyLine/data/questions/ql_baseline.yml
Fix #412
In practice, this isn't too urgent because the Weaver is supposed to generate a custom `objects` block for all "people", but this will help people who follow the guidance on people names and don't use the Weaver.
> Add objects for some nouns we recognize in the Weaver

- docassemble/AssemblyLine/data/questions/ql_baseline.yml
Fix #423 
This will fix methods like `pronoun_possessive` if the person selected "business" on the screen that asks "Is this a business, or a person?"
```yaml
---
include:
---
code: |
other_parties.gather()
---
question: |
${ other_parties[0].pronoun_possessive("apple") }
```
> Add a default gender of a business

- docassemble/AssemblyLine/al_document.py
Fix #338
This is a subtle mistake that will only appear when:
1. Someone uses the ALAddendum class
2. They use our stock ALAddendum DOCX template, or one based off of it
3. They customize the `headers` attribute and the existing attribute names are not descriptive
In most circumstances, someone likely used a custom addendum file or didn't know to set the `headers` attribute.
I also took the chance to refactor the code so it uses `next(` rather than creating a full list of dictionary items.
> Fix the `key` function to return key of first dictionary item instead of value of first dictionary item

- docassemble/AssemblyLine/data/questions/al_settings.yml
- docassemble/AssemblyLine/data/static/al_audio.js
Quick fix I realized testing on a local docassemble server: we still turn on `speak_text`, even if voiceRSS isn't setup on the server. Given that the [DA docs on speak_text](https://docassemble.org/docs/special.html#speak_text) say that speak text just won't work without voicerss being turned on.
I've tested locally, and the speak text doesn't turn on unless you enable it in `voicerss['enable']` in the config, so it doesn't turn on broken speak text on my local server, but still works correctly on the Dev server.
> Speak text fixes

- docassemble/AssemblyLine/al_document.py
A little esoteric, but when you use the ALExhibitDocument class, it defaults to giving each exhibit a cover page like `A`, `B`, etc. The `auto_labeler` attribute lets you override this function to use a different function that takes a list index and returns a suitable sequential label, like [item_label](https://docassemble.org/docs/functions.html#item_label).
This PR just makes it easier to specify the `auto_labeler` attribute when you create an ALExhibitDocument object. Specifically, you can now do it in the `objects` block.
Fix #394
Also spotted a bug in the _update_labels() method.
> More convenient place to customize `auto_labeler` in the ALExhibitDocument class

- docassemble/AssemblyLine/data/questions/al_visual.yml
- docassemble/AssemblyLine/data/static/al_audio.js
- docassemble/AssemblyLine/data/static/styles.css
Changes made:
* added a simple alt text to our logo image. There's a lot of differing information out there about what alt text to use (I found [this flow chart](https://www.w3.org/WAI/tutorials/images/decision-tree/) when developing), but I think going by the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/alt#icons_or_logos), and [this good blog post](https://davidmacd.com/blog/what-is-pure-decoration-alt-text-in-wcag.html) by a WCAG member, is a good idea. Those say to use some simple alt text (just the project's name) on images and logos that aren't purely decorative
* Make the audio buttons have the same names as aria labels. 
From https://www.w3.org/WAI/WCAG21/Techniques/failures/F96:
> "When speech input users interact with a web page, they usually …
> Making our theme accessible

- docassemble/AssemblyLine/data/questions/al_visual.yml
Added an alt_text attribute to an objects block, but forgot that DA
doesn't re-run those for existing sessions, so will just complain instead.
Love when normal program invariants just go out the window /s
Should fix #466, can't directly check until commited though, can you check @nonprofittechy?
> Make al_logo alt_text attr backwards compatible

- .github/workflows/unittests.yml
- .gitignore
- docassemble/AssemblyLine/al_general.py
- docassemble/AssemblyLine/requirements.txt
- mypy.ini
Actually starts running mypy on each commit though the existing unittest action. Necessary to make sure that our types are correct.
Started off in the [suggested state](https://breadcrumbscollector.tech/mypy-how-to-use-it-in-my-project/) of just ignoring errors that occur from third party libraries. Eventually we might want to add stubs for other libraries like the country stuff, or we can make it so that those libraries have types themselves (:eyes: docassemble :eyes:). Probably worth it at some point to look through everything and make sure there are types where there should be.
> Mypy action

- docassemble/AssemblyLine/data/questions/al_visual.yml
DA puts the logo item inside a span, and only spans be a part of other spans, not divs.
Valid HTML is [success criteria in WCAG](https://www.w3.org/TR/WCAG21/#parsing), so we should change, even though it displays fine as is.
Was caught using https://validator.w3.org/nu/?doc=https%3A%2F%2Fapps-dev.suffolklitlab.org%2Frun%2FEFSPIntegration%2Fany_filing_interview, which I am currently integrating into Kiln as well to catch future errors like this.
> Make our Visual HTML valid

- docassemble/AssemblyLine/al_document.py
Can be used like this:
`${ pdf_bundle.as_pdf(pdfa=True) }`
Also corrected some mypy issues on other interfaces where you don't need
the pdfa argument, but we had to add to to make the function signatures match.
Fixes #402. Should add some documentation about it too. Checked using this interview yaml:
```yaml
include:
- al_package.yml
---
question: |
First Question
continue button field: axych
---
question: |
Here is your document.
subquestion: |
${ single_pdf_bundle_1.as_pdf(pdfa=True) }
---
objects:
- single_pdf_bundle_1: ALDocumentBundle.using(elements=[pdf_1], pdfa=True, title="One pdf", filename="single_pdf_1" )
---
objects:
- pdf_1: ALDocument.using( title="PDF 1", filename="pdf_doc_1", enabled=True, has_addendum=False )
---
attachment: 
variable name: …
```
> Add PDF/A support to output docs

- docassemble/AssemblyLine/data/questions/al_visual.yml
Fix #492
This is not a prominent feature--I'm envisioning it might be used for debugging, developers, and very eager users who want to "own" their data.
Access via the footer Share button | Export my answers to a file
> adds an "export to JSON" button to the "Share" screen

- docassemble/AssemblyLine/data/static/styles.css
Was originally #408e30, which has a contrast of only 4.09 on a white background.
Darkens the color to #3b842c, for a contrast of 4.64, well above the WCAG minimum of 4.5.
> Increase contrast of docassemble's term coloring

- MANIFEST.in
Following the instructions in https://mypy.readthedocs.io/en/latest/installed_packages.html#creating-pep-561-compatible-packages.
> packages that supply type information via type comments or annotations in the code should put a py.typed file in their package directory. 
The standard docassemble package data should take care of finding the file.
> Distribute type information as a python package

- docassemble/AssemblyLine/al_document.py
Needed to finish up the ALExhibitDocument, adding bates numbering and OCR. I want to test a bit more on the dev and test servers, but running on a local docassemble, things were fairly stable. The default for `auto_ocr` and `add_page_numbers` is false, so this won't change any existing behavior or make anything unstable yet.
Here's the test interview I used:
```yaml
include:
- al_package.yml
---
code: |
exhibits.exhibits.gather()
if not exhibits.exhibits.ocr_ready():
waiting_screen
else:
final_screen
---
event: waiting_screen
question: Waiting
reload: True
---
event: final_screen
question: |
Here is your document.
subquestion: |
${ single_pdf_bundle_1.as_pdf(pdfa=True) }
---
objects:
- single_pdf_bundle_1: ALDocumentBundle.using(elements=[exhibits], pdfa=True, title="One …
```
> Exhibit improvements

- docassemble/AssemblyLine/al_document.py
- docassemble/AssemblyLine/data/questions/al_question_test.yml
Made a small refactor to logic in enabled_documents() and added an `is_enabled()` method that tracks the logic that was in `enabled_documents()`. This allows us to use a generator expression, so that we can return `True` as soon as we figure out at least one document is enabled.
Fix #503
> Do not show `send_button_html()` if there are no enabled documents in a bundle

- docassemble/AssemblyLine/data/questions/al_visual.yml
Fix #517
Note that in many cases, a server-wide value for this setting doesn't make as much sense as a branding-package specific value, but we do ask people for this value in the installation script and it's used by the bare GithubFeedbackForm already.
> Pull in the default value of `github_user` from the config instead of assuming "suffolklitlab"

- MANIFEST.in
- docassemble/AssemblyLine/al_document.py
For purposes of testing, this defaults to giving a unique suffix to the "preview" version of a PDF as requested by @plocket for ALKiln
Incidentally, this also gives a way for the author to rename an ALStaticDocument PDF (#222)
Fix #506, fix #222
> Append '_preview' by default to PDF filename generated with the "preview" key

- docassemble/AssemblyLine/al_document.py
Fixes an error caused by an error when trying to use nested ALDocumentBundles.
> ALDocumentBundles need `is_enabled` too

- MANIFEST.in
- docassemble/AssemblyLine/data/questions/al_saved_sessions_store.yml
- docassemble/AssemblyLine/data/questions/interview_list.yml
- docassemble/AssemblyLine/data/static/styles.css
- docassemble/AssemblyLine/sessions.py
- mypy.ini
- setup.py
This adds `interview_list.yml`, a replacement interview for the "My interviews" page. An admin can configure Docassemble to use this interview instead of the internal "My interviews" page.
Importantly, this replacement page:
1. Implements some usability suggestions from both Bentley and Theory and Principle
2. Lets the user navigate between Answer Sets and ordinary sessions
3. Is faster than the built-in interviews page because it does not load all interview data into memory to display the list of interviews.
It respects the relevant configuration options, such as `interview page heading`, `interview page title` and `interview page pre`. More extensive customization can be made by `including` this interview into another interview.
Fix #237
Fix #520 
Fix #526 
Fix #493
The `interview_list` …
> Create a replacement page for "My interviews"

- docassemble/AssemblyLine/al_document.py
Fixes #538
An example playground to play around with, simply upload a `my_pdf.pdf` file to that project:
```yaml
---
include:
- docassemble.AssemblyLine:assembly_line.yml
---
objects:
- attachment: ALStaticDocument.using(title="Attachment", filename="my_pdf.pdf", has_addendum=False)
- instructions: ALStaticDocument.using(title="Instructions", filename="my_pdf.pdf", has_addendum=False)
- additional: ALStaticDocument.using(title="Additional", filename="my_pdf.pdf", has_addendum=False)
---
code: |
attachment.enabled = True
instructions.enabled = True
additional.enabled = True
---
objects:
- al_user_bundle: ALDocumentBundle.using(elements=[instructions, bundle], filename="appearance.pdf", title="Download all forms")
---
objects:
- bundle: ALDocumentBundle.using(elements=[attachment, …
```
> First check if the bundle's enabled attribute is on

- docassemble/AssemblyLine/sessions.py
- setup.py
Now we're on python 3.10, there's a `zoneinfo` directly in python, and the `backports.zoneinfo` module doesn't exist.
Adds a try-except for the import, and additionally install the `backports.zoneinfo` package when AL is installed (without which, it will error on a fresh DA instance).
> DA 1.4.0 compatibility

- docassemble/AssemblyLine/al_general.py
- docassemble/AssemblyLine/data/questions/ql_baseline.yml
A small collection of new, optional ALAddress enhancements:
Fix #213 - Provide a helper method to get the "normalized" address as known by Google, even if user provides a neighborhood instead of city name
Fix #127  - Provide an optional way for unhoused people to describe as much of their address as possible. Adjusted address.block(), line_one() etc. so they can handle addresses provided with this feature
Fix #535 - Add a parameter to show/hide the county field in address_fields() method
Small test YAML:
```yaml
---
include:
---
question: |
Address
fields:
- code: |
users[0].address_fields(allow_no_address=True)
---
question: |
subquestion: |
${ users[0].address.on_one_line() }
${ users[0].address.line_one() }
${ …
```
> Address improvements

- docassemble/AssemblyLine/al_general.py
- docassemble/AssemblyLine/data/questions/test_alcourts.yml
- docassemble/AssemblyLine/data/questions/test_question_library.yml
- docassemble/AssemblyLine/data/sources/test_question_library.feature
`hide if` will hide the field if the variable isn't present.
Also adds a simple ALKiln test to look for things like this again, just in the question library versions of address, no address, and contact info. ALKiln test passes locally.
> Fix no address

- docassemble/AssemblyLine/data/questions/al_saved_sessions.yml
- docassemble/AssemblyLine/data/questions/interview_list.yml
- docassemble/AssemblyLine/data/static/interview_list.css
- docassemble/AssemblyLine/sessions.py
- Make the clickable link the form title again, not the subtitle
- Add some new CSS classes to allow more customization of layout
- Default the form title to being bold
If tests pass, I'll go ahead and merge as this is a minor revision to the last PR and doesn't need a full review. This feature is currently only being evaluated by ILAO although hopefully we'll deploy it live soon.
> Switch back to the clickable link being form title, not subtitle

- docassemble/AssemblyLine/data/questions/ql_baseline.yml
Fix #564. Docket number, as far as we can tell with the dozen or so states we've interacted with, is a pretty Massachusetts-specific term. The more general term is "case number". This changes the phrasing of "Docket number" to be "case number" so that people in other states can get better interviews out of the box.
See https://github.com/SuffolkLITLab/docassemble-ALMassachusetts/issues/7 which will move the docket number phrasing to ALMassachusetts, where it is the less confusing term
> Rename "docket number" to case number

- docassemble/AssemblyLine/al_general.py
```
---
include:
- docassemble.AssemblyLine:assembly_line.yml
---
question: |
${ other_parties[0].initials }
```
> Initials shouldn't trigger last name for a business

- docassemble/AssemblyLine/sessions.py
Currently on small screens, if the title of the form uses PascalCase, it will bleed into the second column.
This change:
- Inserts an invisible space (zero width space) into PascalCase words so there is a natural break point
- Turns on the bootstrap text-break utility so that further breaks can happen even in the middle of a word instead of breaking the display
Fix #568
> Fix session list on small screens

- docassemble/AssemblyLine/al_general.py
Checks if the google maps API is present on the server, and if it isn't, does not use address autocomplete in `ALAddress.address_fields()`.
Not necessary for our servers, but helpful when running on local servers, and for users who might not wath Google autocomplete enabled.
> Don't turn on address autocomplete if not enabled

- docassemble/AssemblyLine/al_document.py
On older objects, the attribute might not exist, so make sure it's updated to the standard default. I think this was the only place where we weren't setting this value at the beginning of functions.
This error has shown up on the production server in both the Name change interview and the 209a on 9/14 and 9/15.
> Check if the `suffix_to_append` attribute exists

- docassemble/AssemblyLine/data/questions/al_code.yml
- docassemble/AssemblyLine/data/questions/al_settings.yml
- docassemble/AssemblyLine/data/questions/ql_baseline.yml
Fix #585
This just makes the changes we discussed on our call today. It's a pretty simple fix but touches most of our interviews so I welcome additional feedback I missed on the call.
I added a new flag variable, `al_form_requires_digital_signature` which can be used to add a third option that's currently missing: "sign after I print". When this is chosen, the `x.signature` attribute will be defined as `DAEmpty()`
> Improve usability of signature question

- docassemble/AssemblyLine/data/questions/al_code.yml
- docassemble/AssemblyLine/data/questions/ql_baseline.yml
When you are directly comparing the users to the plaintiffs, DA will try to gather both of the objects. This is fine if `users` is `plaintiffs`, but if the users are the defendants instead, it will trigger a infinite loop screen, since `other_parties` has been set to `plaintiffs`, and it's trying to gather `plaintiffs` before being able to fill `other_parties`.
Additionally, uses `user_role` instead of `user_ask_role`, which will always ask for the user's role in the case, even if it's a form that always done from one side, or we can detect what side of the case the user is on (as with e-filing).
Would like to do some additional testing with this on the dev server, but that might take a bit, since I don't know which interviews to test with. I'll make sure the ALAffidavit and the …
> Use `user_role` over users == plaintiff

- docassemble/AssemblyLine/data/questions/interview_list.yml
- docassemble/AssemblyLine/sessions.py
> Show answer sets even if they are on "step 1" (as answer sets don't usually have more than 1 step)

- docassemble/AssemblyLine/data/static/styles.css
Commonly in review tables, if we show the signature it will be too big for it's column. This extra CSS makes it small enough to fit in the column, which looks less buggy.
Will consider pushing this upstream if I can reproduce outside of our interviews, but not prioritizing that.
> Decrease the size of images in tables

- docassemble/AssemblyLine/al_document.py
- docassemble/AssemblyLine/data/questions/ql_baseline.yml
- docassemble/AssemblyLine/data/questions/test_alexhibit_maxsize.yml
Also give suggested remaining upload size in human readable file sizes in errors and in between upload screens.
Test is in new file called `test_alexhibit_maxsize.yml`, as it's not easily tested in a unit test.
Made this because e-filing into Tyler will require size limits on the overall size of the submission, not just each individually uploaded file like we have now. Unfortunately, the existing approach of "send the documents as a downloadable link instead of sending in the email" won't work, as Tyler's system has a max limit, and I think we want to tread carefully about using external documents not in the filing, as it'll force the courts to act differently with our filings.
Also found a bug (that [I reported in the docassemble …
> Added a max size feature to the ExhibitDocument

- .github/workflows/publish.yml
Will announce new tagged releases on pypi and github to teams. Fixes #547
A copy is working in my testing repo: https://github.com/BryceStevenWilley/docassemble-TestALPypi/actions/runs/3381057069/jobs/5614534406 (will be deleted after this is merged).
A screenshot of what the teams announcement will look like: 
The teams bumphook should already be set as an org wide secret.
> Teams bump hook, in a github action

- docassemble/AssemblyLine/al_general.py
- docassemble/AssemblyLine/test_al_general.py
- pyproject.toml
Originally, was ", ", which is def a bug.
Suggested by @mnewsted
> If address is empty, `on_one_line()` will be empty

- docassemble/AssemblyLine/al_document.py
- docassemble/AssemblyLine/al_general.py
- docassemble/AssemblyLine/sessions.py
- pyproject.toml
Apparently not allowed by PEP-484. Personally, I've gotten used to it, but I remember being confused by it, and the change isn't too bad.
Is the real fix to https://github.com/SuffolkLITLab/docassemble-AssemblyLine/actions/runs/3413494344/jobs/5680263993.
Open to leaving the option in, but I'm also always for more strict and direct types.
> No more implicit optionals in function signatures

- docassemble/AssemblyLine/al_document.py
- docassemble/AssemblyLine/test_al_document.py
Fix #243 
Sample interactive test:
```yaml
---
modules:
- .al_document
---
code: |
text_input
display_results
---
objects:
- myfield: ALAddendumField.using(field_name="text_input")
---
question: |
Enter some text
fields:
- Overflow trigger: myfield.overflow_trigger
datatype: integer
- Text: text_input
datatype: area
rows: 5
---
event: display_results
question: |
Results
subquestion: |
${ single_to_double_newlines(myfield.safe_value(overflow_message="...", preserve_newlines=True, preserve_words=True)) }
${ single_to_double_newlines(myfield.overflow_value(overflow_message="...", preserve_newlines=True, preserve_words=True)) }
```
> don't cut off text for addendum in mid-word

- docassemble/AssemblyLine/al_document.py
I noticed I had skipped this API, but it's the more common way of invoking the addendum code.
> Addendum whole words - integrate with ALDocument-level version of the API

- docassemble/AssemblyLine/data/questions/ql_baseline.yml
> Remove words 'the' and 'project' from opening screen 

- docassemble/AssemblyLine/al_document.py
- docassemble/AssemblyLine/data/questions/al_document.yml
Triggers an event in `al_document.yml`, which calls back into a module.
`--skip-text` is the fastest and probably what we want. Tried with `--redo-ocr` , but it was very slow (4 minutes for just 14 pages), and only 3 of those pages had any text. Don't think `--force-ocr` is what we want.
Difficult to get performance on it, since it runs in celery on a random worker, so I can't really use `py-spy`, but it's probably good enough for now.o
Still leaving things flexible as to when in an interview you want to wait for the fully ocr'd text; at these speeds, I'd be okay with making people wait before the final screen, but I'll also try putting e-filing in the background, if it's not too hard.
I've been testing with:
```yml
---
include:
- docassemble.AssemblyLine:assembly_line.yml
---
objects:
- …
```
> Change OCR to use ocrmypdf in the background

- docassemble/AssemblyLine/data/questions/ql_catchall.yml
For now, this adds an optional include: `ql_catchall.yml` which a developer can incorporate to turn on the DACatchAll feature. I think it might help current students of myself and @colarusso if we integrate this with the MassAccess theme and install on the dev server, but we should try it out for a bit before deciding if it's something to enable globally.
I'm especially interested to see what we'll want to add to handle things like: invalid object references (e.g., we can probably turn unknown object references into ALIndividuals and unknown list references into ALPeopleLists). But I'm not sure best how to handle that yet--maybe we'll come up with some regexes when we figure out what common developer errors are.
Fix #618
> First version of DACatchAll

- docassemble/AssemblyLine/data/static/styles.css
Before this change, you aren't able to see that you are keyboard tabbing over the back button, as the value bootstrap uses to color the shadow doesn't have a value for the `daquestionbackbutton` class, only the `btn-primary` class. Improves [WCAG 2.4.7](https://www.w3.org/TR/WCAG21/#focus-visible).
TBH, I'm not a huge fan of the default focus indicators in bootstrap, they don't have enough contrast. But that will likely have to wait for a different PR, as it's a much larger change.
Picture of the change below:
> Add focus shadow for back button

- docassemble/AssemblyLine/al_general.py
Necessary to safely test on any new server being spun up.
Debug: true shouldn't be on in production servers.
> `will_send_to_real_court` false if debug == True

- docassemble/AssemblyLine/data/questions/al_visual.yml
Creates a custom error page, with an optional link to download the form in progress. The download depends on the `skip undefined` parameter being correctly used on the attachment block.
In addition, this adds an "Exit and delete answers" link (#615) and a link to download the forms in-progress at any time, per discussion on Coding Deep Dive on 11/20/22 and broader discussion in #232
Fix #620 
Fix #615 
`DACatchAll` is turned on on our development server. If you want to simulate an error, one that I have been trying is triggering a hashing error. E.g., `users[{}]` in the interview order block.
I probably want to keep thinking about this a bit more over the next week or two, but it should be ready to look at. Specifically, I might want to add some features to the GithubFeedbackForm
> Add a custom error action

- docassemble/AssemblyLine/data/questions/al_saved_sessions_store.yml
Fix #625
Can still consider expanding the API to allow conditional encryption of answer sets without changing the answer set target, but I think this is the right default for now.
> Make answer sets unencrypted to match interview state

- .github/workflows/unittests.yml
Also bump to python 3.9: closer to still working with python
3.8 for older docassemble versions, but still on by default
in ubuntu 22.04, the new test runners on github.
Should also try to cache pip dependencies. Should work,
will need to re-run the job to see if that works, (though it's
less of a priority).
> Fix unittest action

- .github/workflows/unittests.yml
- docassemble/AssemblyLine/requirements.txt
Moved the unittest action externally, in the [ALActions](https://github.com/SuffolkLITLab/ALActions) repo.
I also moved the publish step over, but the unittest one is a lot easier to test (and is currently breaking in all repos, so going forward, I want to fix things once and have the action fixed across all repos).
> Move unittest action externally

- docassemble/AssemblyLine/data/questions/al_visual.yml
This covers a suggestion in #260 to give users a little more context in their progress on the form. It doesn't add sections to the interview, but we already have open issues in the Weaver for that (See https://github.com/SuffolkLITLab/docassemble-ALWeaver/issues/45), which is really the only place we can help authors with this task.
Also see #320
Fix #260
> Add a link to "original form" on the default about page, if it exists and looks like a valid link

- docassemble/AssemblyLine/data/questions/ql_baseline.yml
2 or more trailing whitespaces in markdown will add a line break (<br>) to the line. One of the trailing whitespaces that were separating out the 3 introduction steps for each AL interview was mistakenly removed in https://github.com/SuffolkLITLab/docassemble-AssemblyLine/commit/57df4abad5af35d86793527ba7f1a898cc19147a#diff-55dff7108dded7bbc3ce8459dd669a79baec6674c1558af86f66dbc878268288L44, putting steps 2 and 3 on the same line.
This PR replaces those trailing whitespaces with a more explicit `<br>`.
> Readd newlines between each step on intro screen

- docassemble/AssemblyLine/data/questions/al_visual.yml
- Use better formatting to more closely match existing DA 501.html template
- Make it possible to completely hide the technical information when verbose errors are disabled with the existing Docassemble error configuration (https://docassemble.org/docs/config.html#verbose%20error%20messages)
Test interview:
```yaml
---
include:
---
question: |
${ users[dict()] }
```
> Cleanup appearance of error action page

- LICENSE
- docassemble/AssemblyLine/al_document.py
- docassemble/AssemblyLine/data/questions/test_aldocument.yml
- docassemble/AssemblyLine/data/static/aldocument.css
- setup.py
Closes #563, Closes #562, alignment of document download table buttons vs. document email section parts, plus other alignment and styling issues. I tried to limit the changes to the email section as people are using that styled as-is right now. Here are some notes from our deep dive doc as well:
* Add a new parameter to download_list_html() to include a send email button row. But it will be a copy of the feature - we won’t delete the existing send_button_html() method.
* Fix the send_button_html() method html strings to remove the H5, though keep the styling
* Right align the send button of the separate email section,
* Remove the big gutter between the buttons and the text
Remade this PR because the pfs/black changes on the old branch caused a conflict with my updates.
Also closes #177 I …
> Close #563 Add send email table row and change styling to align buttons

- docassemble/AssemblyLine/sessions.py
Got a request to make the title of the original source of an answer set optional. Minor change for now. Perhaps we should consider a different way to generate this screen given the many ways people are looking to customize it right now, but it should be OK to grow a bit more configurable before we reach a limit.
> Make source interview title optional in interview_list() function

- docassemble/AssemblyLine/al_document.py
Fix #683 
We released the new Affidavit of Indigency as an ALDocumentBundle, not a plain ALDocument anymore. I forgot to make sure it worked in all scenarios; it doesn't work when you show a download screen with DOCX downloads because of the missing is_docx() method.
I went through and tried to implement a basic version of all of the ALDocument methods on ALDocumentBundle so we can try to avoid other issues like this in less commonly tested branches.
> Document bundle compatibility

- docassemble/AssemblyLine/data/questions/al_reminders.yml
- docassemble/AssemblyLine/data/questions/assembly_line.yml
Fix #333
Opening as a draft for now, just to let other folks play around with the structure and see if the API is reasonable.
Here's a small interview I was using to experiment with launching the reminders manually:
You may want to try copying the format of the `al_reminders` block to add some of your own reminders, add additional reminder templates, etc.
```yaml
---
include:
- al_reminders.yml
---
code: |
users[0].mobile_number
al_user_wants_reminders
---
variable name: al_reminders
data:
filing_documents:
description: Filing these documents
date: ${ today().minus(days=3).format("yyyy-MM-dd") }
email template: al_reminder_filing_template
sms template: al_reminder_filing_template  
---
question: |
Click the button to launch the event …
```
> Create a framework to simplify adding sending users reminders and other alerts

- .github/workflows/run_form_tests.yml
Tests shouldn't need to run when change the README or the CHANGELOG.
> Experimenting with not running Kiln on non-functional commits

- docassemble/AssemblyLine/al_general.py
- docassemble/AssemblyLine/test_al_general.py
Fix #706 
Basic algorithm to decide when to add the word "Unit":
1. Check if the unit is not numeric
2. Check if it includes at least one space
3. Check if it uses a known word, like "apt" but the user left out the space
If all tests fail, we add the word Unit.
> handle more situations where user unintentionally left "Unit" out of address field

- .github/workflows/run_form_tests.yml
- docassemble/AssemblyLine/al_general.py
- docassemble/AssemblyLine/test_al_general.py
Fix #672 
I also realized Jonathan's original code had some mistakes, including a default "he/him/his" when gender wasn't one of "male", "female" or "other."
Finally, this code handles the user's preferred pronouns in priority to the pronouns that come from the default of their gender if the author has a question that asks for pronouns (and we can unambiguously parse those pronouns)
> Use "it" for a business, correctness for pronoun methods and handle preferred pronouns

- docassemble/AssemblyLine/data/questions/al_visual.yml
fix #723
Adds a new user-facing magic keyword: `al_menu_items_custom_items` which should be a list of menu items. Custom items are shown before default menu items.
Each menu items follows the Docassemble menu item format, which is a dictionary with the keys `url` and `label`. It can be convenient, and readable, to use a `data from code` block to define the menu items, but you can use any method to create the right Python datastructure.
Optionally, you can add a key `hidden` which contains a True/False value. If the value is `True` the menu item won't be shown. This can be used to dynamically show or hide the menu item on a given page. If the value is dynamic, you should add a `reconsider` modifier on the block that defines `al_menu_items_custom_items`.
E.g.,
```
reconsider: True
variable …
```
> More flexible API for menu items

- docassemble/AssemblyLine/al_general.py
- docassemble/AssemblyLine/data/questions/al_visual.yml
- docassemble/AssemblyLine/test_al_general.py
Fix #262 
like #726 does for the drop-down menu, this creates a method to control the navigation items on the left in a more declarative way. The author can provide datastructure that is recalculated fresh on whatever basis makes sense for the interview (reconsider modifier, inline call to reconsider, or `depends on` modifier as appropriate). The datastructure will list every potential menu item and then put the rule for turning the item on or off in the optional `hidden` key.
Because we have a lot of existing interviews that use the simpler `sections` syntax to define static sections, this behavior is turned off by default.
Example:
```
---
code: |
enable_al_nav_sections = True
---
reconsider: True
variable name: al_nav_sections
data from code:
- item1: |
"Label1"
- item2: |
"Label2"
- …
```
> More declarative method for defining navigation sections

- docassemble/AssemblyLine/al_courts.py
- docassemble/AssemblyLine/al_document.py
- docassemble/AssemblyLine/al_general.py
- docassemble/AssemblyLine/language.py
- docassemble/AssemblyLine/sessions.py
Fix #178 
This just adds google-style docstrings for every class, method and function so we can improve our auto-generated documentation pages. Used GitHub copilot as an assistant but I've checked these all for correctness and minor tone/style changes from the CoPilot first drafts.
Also added some types that were missing.
I added one new method `geocode` because we were using the legacy phrasing `geolocate` (a misnomer that was in the Docassemble code base for several years). Otherwise, this should have no functional changes, only new documentation and change of documentation style to Google. Feel free to do a light review--any egregious documentation error should be corrected but we're mostly filling in missing information.
> Better docstrings

- docassemble/AssemblyLine/data/questions/al_visual.yml
- docassemble/AssemblyLine/data/questions/ql_baseline.yml
Fix #736
Looks like this was meant to be a decoration for the main intro page. I found the icon w/ the attribution, but it's now behind a paywall so we can't easily just add it back in anyway.
It's not a bad idea to have some visual here, but given #461 and the fact that this decoration appears to have *never* been visible, going to just remove it for now as the safest choice.
We can decide to add more graphics later, probably shouldn't do it in the default theme without notice though.
> remove icon from intro screen that was never displayed

- docassemble/AssemblyLine/data/questions/al_code.yml
- docassemble/AssemblyLine/data/questions/al_visual.yml
Makes it easier to be reused in unstyled interviews, while keeping all styled and unstyled interviews the same.
Fixes #355.
I think the Assembly Line Kiln tests should be good enough to test this fully, but I might manually check what the trigger variable looks like in a few different question screens.
> Moved ALKiln HTML to a template in al_code

- docassemble/AssemblyLine/al_document.py
Say specifically where the zip title is used, improve a few PDF/A docstrings, and pass through pdfa param in a corner case.
Fixes #734, to the best that we can.
> Better docstrings for `as_zip(title="", ...)`

- docassemble/AssemblyLine/data/static/styles.css
fix #748
This just mirrors the defaults in various production repos so more projects will work out of the box:
https://github.com/SuffolkLITLab/docassemble-ALWeaver/blob/fef677dd2daa9dd65d04b5621841f8e464910e86/docassemble/ALWeaver/data/static/styles.css#L25
https://github.com/SuffolkLITLab/docassemble-ALThemeTemplate/blob/2b0a0140a816c12f366a93feea1cdc7cdb95eb4e/docassemble/ALThemeTemplate/data/static/colors.css#L7
> Limit maximum height of logo

- docassemble/AssemblyLine/language.py
Corrected behavior of languages.py; it now will use a local languages.yml in the rare event that it exists, but correctly loads the package version of languages.yml in every other circumstances.
This was a breaking issue in the 209A but only visible on the test server so far.
> Safer loading of YAML file with language names

- docassemble/AssemblyLine/data/questions/al_visual.yml
In https://github.com/SuffolkLITLab/docassemble-ALWeaver/pull/835, we moved a lot of the metadata from the `interview_metadata` variable to the `metadata` block. This PR finishes the job, and allows AssemblyLine to look in the `metadata` block, if there isn't an `interview_metadata` at all. This works for newly weaved forms, and I've confirmed that it works great for interviews with and without `interview_metadata` as well.
The only tricky part was that `original_forms` in the metadata block has become a list of URLs, instead of just one. IMO that's fine, but I had to refactor some things and define one more mako variable to make the code clean. When there's only one original form, it'll still show as normal, and if there are more than one, it'll show raw URLs for each. Which is fine, not …
> Move Metadata over to metadatablock

- docassemble/AssemblyLine/al_document.py
I tend to "follow the code", and it took be a little bit to figure out what the default template was actually used here. Figured I'd put it in the documentation to make it clearer to folks who might look at the API documentation.
> Update send_button_html docs

- docassemble/AssemblyLine/al_courts.py
If you refer to plain file name without the path (i.e. "my_courts.xlsx") in an objects block, and then include that YAML from a different package, ALCourtLoader will fail to load the courts correctly, because it thinks that "my_courts.xlsx" should be in that different package, instead of in the original.
This fixes that by using
`docassemble.base.functions.this_thread.current_question.package`. Took the code from DAStaticFile._get_unqualified_reference, which is throughly used. Manually tested using https://github.com/mplp/docassemble-mlhframework.
> Load court list from correct package

- docassemble/AssemblyLine/data/static/al_audio.js
Otherwise, we end up adding our controls twice, sometimes with the same id and everything, so the second isn't displayed right.
Additionally, I added the event param to the `daPageLoad` callback function; when I was trying to debug this, being able to use the browser JS debugger was very useful, but I couldn't edit the running code at all, so having more event information to look at would have helped a bunch.
* Downstream issue: https://github.com/mplp/docassemble-mlhframework/issues/15
* Related AssemblyLine issue / alternate fix: https://github.com/SuffolkLITLab/docassemble-AssemblyLine/pull/784
> Don't add our al_audio if existing node is hidden

- docassemble/AssemblyLine/data/questions/interview_list.yml
Here's the high level overview (also possible to get it from the code. currently this message is duplicated in one long comment at the top of the file)
Customize by:
1. Editing the global configuration (see below), or
2. Including this file and overriding the default values in a replacement YAML file
Relevant options and defaults:
```yaml
app homepage: https://courtformsonline.org
assembly line:
enable answer sets: True
interview list:
page title: In progress forms # Title of the tab in your browser
page question: In progress forms
page subquestion: null
new form label: Start a new form
new form url: https://courtformsonline.org
logo url: null # Defaults to `app homepage`
logo image url: https://app.yourserver.org/packagestatic/docassemble.AssemblyLine/ma_logo.png
logo image alt: Logo …
```
> Refactor of interview list page

- docassemble/AssemblyLine/al_general.py
- docassemble/AssemblyLine/data/questions/ql_baseline.yml
Minor changes that address #281. More details in that issue, but I don't think it's possible to get the full state dropdown for each country without messing up Google autocomplete, so when the country is an input, we turn the state list into a text box (I tried swapping out a dropdown for just the US and text input for other countries, but Google autocomplete also has a problem with that).
Only other changes were to change the "State" label to "State / Province" when the country is an input, and a few comments / docs, for accuracy.
Also relevant to https://github.com/mplp/docassemble-MLHMotionRegardingChildSupport/issues/6.
> International addresses

- docassemble/AssemblyLine/al_general.py
- docassemble/AssemblyLine/data/questions/al_reminders.yml
- docassemble/AssemblyLine/data/questions/al_visual.yml
- docassemble/AssemblyLine/data/questions/ql_baseline.yml
* `is_sms_enabled()`, sees if the `twilio` config in the settings are non-empty (doesn't check that they work)
* Turns off mentions of texting in the "Share" page
* Turns off option to get texts from the reminder system
* Turns off options to text the link to yourself when signing
The only change I could see being suggested is to move `is_sms_enabled()` (and `is_phone_or_email()`, even thought it's been in AL for a while) to the Toolbox. IMO, it's not worth splitting highly coupled functions between two different packages, but will happily do it if suggested.
Fixes #411 for texting, not for email, but as mentioned in the meeting this morning, most of our users have some sort of email enabled on their server.
> Check SMS is enabled before showing texting opts

- docassemble/AssemblyLine/data/questions/ql_baseline.yml
They likely can and should be edited for each interview, but it's easier for authors to start from an existing block (especially if it prevents them from seeing an error on the review screen).
Related to https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/pull/388
> Add default revisit and table blocks for ALPeople

- docassemble/AssemblyLine/data/questions/al_visual.yml
Very minor note that someone noticed when doing feedback of our interviews. Assembly Line doesn't hypenate it elsewhere: https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/3d0181df9f2c78a87db86e018825cffaf8ce27c4/docassemble/AssemblyLine/data/questions/al_saved_sessions.yml#L60, so this makes us consistent with other text on the screen and ourselves.
> Un-hypenate sign-in

- docassemble/AssemblyLine/data/questions/al_visual.yml
- docassemble/AssemblyLine/data/questions/interview_list.yml
> Remove redundant alt-text on logos

- docassemble/AssemblyLine/project_maintenance.py
- docassemble/AssemblyLine/requirements.txt
Fix #746
This PR introduces a new module `project_maintenance.py` designed to help you automate creating a tracking issue across multiple repositories. It also lets you automatically make a card for the issue on a GitHub next generation project board. Finally, it assists with adding a topic to a github repositories based on their presence on the /list?json=1 endpoint on a given Docassemble server. This topic can later be used to decide which repos need tracking issues to be created for them.
- **Get Package Names**: Fetch package names from a specified Docassemble server.
- **Add Tag to Repositories**: Add a specific tag to repositories within a GitHub organization.
- **Process Packages and Add Tag**: Combine fetching package names and adding tags into a single process.
- **Add Issues and …
> Add New Module for Project Maintenance Automation (adding tracking issues to multiple repos)

- docassemble/AssemblyLine/al_general.py
Also don't pass `show_impounded`
Fix  #816
Test YAML that only works after this change:
```yaml
---
include:
---
objects:
- the_address: Address
---
id: your address
question: |
What is your address?
subquestion: |
Where do you live?
fields:
- Street address: the_address.address
address autocomplete: True
- Unit: the_address.unit
required: False
- City: the_address.city
- State: the_address.state
code: |
states_list()
default: MA      
- Zip: the_address.zip
required: False
---
code: |
users.gather()
users[0].address = the_address
message(users[0].address_block())
```
> Don't pass 'bare' parameter unless it's an ALAddress

- docassemble/AssemblyLine/data/questions/al_code.yml
- docassemble/AssemblyLine/data/questions/al_saved_sessions.yml
- docassemble/AssemblyLine/sessions.py
Fix #825
You can now customize the list of filtered variables when saving or loading a snapshot by adding a new definition of `al_sessions_additional_variables_to_filter`, without having to manually add all of the Docassemble and AssemblyLine variables that should always be filtered.
Tested manually by loading and saving some sessions.
> Make a simpler API for customizing list of filtered variables

- docassemble/AssemblyLine/data/questions/al_code.yml
- docassemble/AssemblyLine/data/questions/al_visual.yml
Proxy variables are generic objects and index variables. I don't think this needs to be added anywhere else.
Closes #823
> Add proxy variables' HTML for ALKiln >=5.9.0 2-column Story Table

- docassemble/AssemblyLine/al_general.py
- docassemble/AssemblyLine/test_al_general.py
Fix #818
Adds 3 new methods directly on ALIndividual to shorten various methods of IndividualName:
* ALIndividual.name_full() = ALIndividual.name.full(middle="full")
* ALIndividual.name_short() = ALIndividual.name.firstlast()
* ALIndividual.name_initials() = ALIndividual.name.full(middle="initial")
> Shorter way to specify name.full(middle='full')

- docassemble/AssemblyLine/data/questions/al_visual.yml
Fix #771 
Adds an optional URL parameter, `hide_hud`, that can be used to hide the "red" text that displays when the server
is in debug mode. This can be helpful if you want to share a link to the interview on a development server and the red text will distract the recipient.
> Add a hide_hud parameter to enable hiding the id/variable/package number

- docassemble/AssemblyLine/data/questions/al_code.yml
As the comments now describe, some servers still need the HTML code to add the trigger variable name to the DOM.
As this is just a comment and doesn't change any functional code, I'm just going to merge it.
> Undo deprecation declaration for "trigger" HTML

- docassemble/AssemblyLine/al_document.py
- docassemble/AssemblyLine/data/questions/test_bundle_parity.yml
Adds a parameter `ensure_parity` to the `ALDocumentBundle.as_pdf()`, and `default_parity` as an attribute of the bundle.
parity means odd or even number of pages. When either parameter or attribute is set, the as_pdf() method of the bundle may pad the output with an additional page, if needed to match the desired parity.
The purpose is primarily to assist with double-sided printing.
- `ALDocumentBundle.default_parity`: can be "odd", "even", or `None`.
- `ALDocumentBundle.as_pdf(ensure_parity)` can be "odd", "even", or `None`. Overrides `default_parity`.
Test document: `test_bundle_parity.yml`.
Example usage:
```
---
objects:
- even_bundle: ALDocumentBundle.using(
title="Even bundle",
filename="the_bundle",
elements=[
the_doc
],
default_parity="even",
enabled=True
)
```
Fix #828
> When using the as_pdf() method of a bundle, add parameter to ensure an odd or even number of pages

- docassemble/AssemblyLine/al_courts.py
- docassemble/AssemblyLine/al_general.py
Fix #840
Currently, when you use the court_loader class in al_courts.py, there's a chance that a column that has a zip code with leading zeros will be interpreted incorrectly.
This fixes it in 2 ways:
1. transforms the `address_zip` column inside the dataframe when it is loaded to zerofill it to at least 5 digits
2. when printing a zip code (.zip attribute) as part of an address, zerofill to 5 digits.
It also adds an API to define a transformation for arbitrary columns of the Excel spreadsheet: defining the `.converters` attribute of the `ALCourtLoader` will now automatically run the converters when the dataframe is loaded. This honors the standard Pandas syntax, where `converters` should be a mapping between the column name and a callable with one parameter.
Ex:
```
---
objects:
- …
```
> Pad .zip attribute with 0 and ensure proper loading from court list

- docassemble/AssemblyLine/al_general.py
> Allow pronoun functions to work when .pronouns is defined as a string rather than DADict

- docassemble/AssemblyLine/al_document.py
It's possible to set a `boolean` as the `overflow_trigger` for an ALAddendumField when the conditions for triggering the addendum don't depend on the length of a list or string. But we weren't properly handling the condition where the `boolean` was `False`.
This handles the `False` condition in the overflow trigger by returning an empty string, which will result in `has_overflow()` returning `False`.
This situation may be a bit unusual, but it might be worth using this pattern when the conditional text is required to be added to the same addendum as other overflow text. In other situations, it would make more sense to create a standard ALDocument with the `enabled` value set.
This also fixes a production bug in the Vermont Divorce package.
> Handle False boolean overflow triggers, not just True

- docassemble/AssemblyLine/data/questions/al_settings.yml
- docassemble/AssemblyLine/data/questions/ql_baseline.yml
This:
* Removes the special case questions that refer to users[0], simplifying the ability to override them. (fix #851)
* Adds a new variable, `al_person_answering`, that defaults to `"user"`, to make the text responsive in a way that addresses the special case for user 0 without assuming that the form is being completed by the user. (#109)
Authors have the freedom to add their own question defining `al_person_answering`, but this is hardcoded in a code block in the stock version of Assembly Line to avoid disrupting the behavior of existing interviews. The only specially handled value is `"user"`. Authors are free to specify options like "attorney", "helper", etc.
Fix #109, fix #851
> Make it easier for developers to customize questions about `users` list - one question for user 0/i and adaptive use of "you"

- docassemble/AssemblyLine/data/questions/demo_search_sessions.yml
- docassemble/AssemblyLine/sessions.py
Adds a new function, `find_matching_sessions`, which can be used to search and retrieve a set of matching sessions across all unencrypted interview sessions on a server.
The expected use case is for an attorney or other advocate to be able to search through their own sessions to find a document they automated for a particular user. It can also be used in a scenario where there is a generic "intake" interview that the attorney wants to use as a starting point to automate future documents with. Search results can be limited to a particular interview or set of interviews, such as an intake questionnaire. 
Searching across sessions that you did not create or were not explicitly shared is limited to 3 user roles by default: admin, developer, and advocate.
Matching is performed entirely based …
> Add `find_matching_sessions` function to enable keyword searching across sessions, based on metadata

- docassemble/AssemblyLine/al_general.py
- docassemble/AssemblyLine/data/questions/test_familiar_disambiguation.yml
Fix #857
Returns the individual's name in the most familiar form possible.
The purpose is to allow using a short version of the individual's name in an unambiguous
way in the interview. For example: referring to the child in a guardianship petition
by first name instead of "the minor". But there may be a problem if context doesn't make
it clear if you are talking about the child or their parent when they share a name.
In order, it will try to use:
* just the first name
* the first name and suffix
* the first and middle name
* the first and last name
* the full name
* the default value, e.g., "the minor", if provided
* the full name
Example usage:
```mako
Who do you want to take care of ${ children.familiar(unique_names=parents + petitioners, default="the minor") }?
```
> Make it possible to disambiguate 'familiar' names

- docassemble/AssemblyLine/al_general.py
- docassemble/AssemblyLine/test_al_general.py
Fix #874 
This PR updates the pronoun, pronoun_possessive, and pronoun_subjective methods in the al_general.py module to provide more robust handling of pronouns, including support for multiple pronouns and custom user-provided pronouns. Key changes include:
* Enhanced Pronoun Flexibility: The methods now support the use of multiple pronouns (e.g., "he/they")
* Parse custom pronouns in .pronouns as a DADict, not just in `pronouns_self_described`
* Don't trigger gender or pronouns: if the pronouns or gender attributes are not defined or can't be parsed, fall back on either a user-provided default (like "the agent") or the person's full name
This may change behavior of some interviews that don't currently, explicitly, trigger a question about pronouns or gender.
> Don't trigger gender, better handling of non-disclosed pronouns

- docassemble/AssemblyLine/al_general.py
This adds a new method, pronoun_reflexive(), to both ALPeopleList and ALIndividual.
A reflexive pronoun is a word like "myself", "yourself", "themselves", "ourselves", "herself", or "himself" that acts upon itself.
When used on a singular person with pronouns they/them or gender "nonbinary", it will return "themself", which is increasingly being used as a standard singular pronoun for a person who is nonbinary or uses they/them pronouns.
When used on a list of multiple people, it will return "themselves".
the pronoun_reflexive() pronoun also respects 1st and 2nd person point of view using the Docassemble standard methods to indicate point of view, including passing the "person" parameter.
> Add support for reflexive pronouns

- docassemble/AssemblyLine/data/questions/demo_search_sessions.yml
- docassemble/AssemblyLine/data/questions/interview_list.yml
- docassemble/AssemblyLine/requirements.txt
- docassemble/AssemblyLine/sessions.py
This PR adds the ability to search through existing sessions to the interview list page.
When searching through sessions, it is also now possible to limit the search results by a particular metadata column. This can be used for access control or other arbitrary ways to limit search results across a server.
This will also be used to support more ways to troubleshoot session searching in the ALDasbhoard
> Add session search feature to interview list page; allow limiting session searching by arbitrary metadata column

- docassemble/AssemblyLine/data/questions/al_visual.yml
Fix #915
Adds a URL parameter, `debug=1`, that allows a developer, admin or advocate to:
1. View the standard HUD
2. Quickly get to the /vars?i=... URL for the running interview file.
These should both help with debugging errors in the production environment more easily.
Note that these parameters aren't available for a regular user.
> Allow more debug operations on production environment

- docassemble/AssemblyLine/custom_jinja_filters.py
- docassemble/AssemblyLine/data/questions/ql_catchall.yml
If you are using a DOCX template, this adds a new Jinja2 filter, `catchall_options(value [implicit], *items)`, that lets you define the options in the template itself. The options will be presented as a drop down menu in the interview.
Template options would typically be provided with a syntax like either of the below examples:
```
{{ my_catchall_field | catchall_options("code1: label1", "code2: label2") }}
{{ my_catchall_field_2 | catchall_options({"code1": "label1"}, {"code2": "label2"}) }}
```
This is useful for situations when you have a very simple interview that you would like to allow an end-user to edit and upload and you have DACatchAll enabled to flag undefined variables. E.g., some legal aid programs use this to request client signatures.
This also adds a filter …
> Support dynamically provided options in the DOCX template file

- docassemble/AssemblyLine/al_general.py
Fix #922 
Checks for definition of name.last before triggering it
> Calling familiar() no longer triggers last name

- docassemble/AssemblyLine/test_language.py
Because `unittest` [no longer works with PEP-420 implicit namespaces](https://github.com/SuffolkLITLab/ALActions/commit/b2f68e2d077764a8256cb747e15fba7a97f19787) (which we are required to use because of docassemble and other python tooling deprecating the old way of using namespaces), we run unit tests with `python -m unittest discover docassemble`.
Starting at the `docassemble` folder changes what `unittest` thinks the namespace is, so the `patch` call needs to patch the `AssemblyLine.language.url_action` function instead. We keep the original patched function (`docassemble.AssemblyLine...`) to make it clear what we are trying to override and for the tests to work when run without the discover feature.
We also change to using `patch` as a decorator, which is it's documented use, and more …
> Fixed failing mock functions in language test

- docassemble/AssemblyLine/al_general.py
- docassemble/AssemblyLine/data/questions/ql_baseline.yml
- docassemble/AssemblyLine/data/questions/test_question_library.yml
Adds a new parameter to the ALIndividual.pronoun_fields() method, `choices`, which allows overriding the default list of choices for `pronoun_fields()`
If the parameter is not provided, we will use a magic variable (from the interview) `al_pronoun_choices`.
The most common expected use case is to remove `ze/zir/zirs` from the list.
(discussion below reflects previous version of this description)
Fix #927
> Allow customizing pronoun list and disabling the neopronoun ze/zir/zirs both case-by-case and globally

- docassemble/AssemblyLine/data/questions/ql_baseline.yml
- docassemble/AssemblyLine/data/sources/test_question_library.feature
This shouldn't affect e-filing screens as they are already customized.
Fix #552
> Use `al_international_phone` datatype for all phone number fields

- docassemble/AssemblyLine/sessions.py
Fix #955 
Refactored both get_interview_metadata() and get_saved_interview_list() which were, by way of Docassemble's `variables_snapshot_connection()`, making use of raw psycopg2 connections instead of the higher-level sqlalchemy connections. Made better use of context manager which should also avoid premature session closing.
I don't recall a reason to use the variables_snapshot_connection() in these two functions, as the rest of the module uses the Docassemble shared `db` object.
`get_interview_metadata()` is used on the al_saved_sessions_store.yml page, and get_saved_interview_list() is used on the interview_list.yml page for basic testing. Testing the search feature particularly should validate this change.
> Don't explicitly close connection, instead use context manager
