SuffolkLITLab/docassemble-AssemblyLine

- docassemble/AssemblyLine/al_document.py
Also a bit of clean up around the area while I was looking for similar errors in the other functions.
> Only use document in HTML table if enabled

- docassemble/AssemblyLine/data/questions/al_visual.yml
- docassemble/AssemblyLine/data/static/al_audio.css
- docassemble/AssemblyLine/data/static/al_audio.js
Addresses #29, but not completely, only as an MVP. If this version actually makes things worse, we can just close this PR and wait till further development can happen. See #29 for a lot more discussion.
> #29 audio UI improvements (MVP)

- docassemble/AssemblyLine/data/questions/al_question_test.yml
- docassemble/AssemblyLine/data/questions/ql_baseline.yml
Fixes #95. Running the test interview should show the fix working.
> Fix #95, ALPeopleList .gather() `i` not found

- setup.py
Needed for https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/pull/380.
> Added ALToolbox as a dep

- docassemble/AssemblyLine/al_document.py
Closes #89. I anticipate changes needed, so I figure I'll start us off. If this is a decent start and you have some specific ideas in mind for improvement, feel free to make changes.
> Close #89, add to documentation for ALDocument

- docassemble/AssemblyLine/data/questions/al_package_unstyled.yml
- setup.py
Going to merge--new file that isn't referenced yet
> Added al_package_unstyled.yml; fix #129

- docassemble/AssemblyLine/al_general.py
- docassemble/AssemblyLine/data/questions/al_code.yml
- docassemble/AssemblyLine/data/questions/ql_baseline.yml
Fix #91  Fix #13 Fix #111
Small additions to the question library; remove obsolete language about sending to someone else on the signature screen
> Question library enhancement

- docassemble/AssemblyLine/al_document.py
- docassemble/AssemblyLine/data/questions/al_visual.yml
- docassemble/AssemblyLine/data/static/aldocument.css
Put send button on same line as email input, hopefully resolving some send button height issues.
> 65 download table

- docassemble/AssemblyLine/al_document.py
- docassemble/AssemblyLine/data/questions/al_question_test.yml
- docassemble/AssemblyLine/data/static/aldocument.js
> Close #189, exclude zip row if only one doc _enabled_

- docassemble/AssemblyLine/al_document.py
I think this will mostly affect files with addenda. Subjectively, this already makes a different on our test file. Thanks @BryceStevenWilley for the profiling in #36
> Low-hanging fruit speedups

- docassemble/AssemblyLine/al_general.py
- docassemble/AssemblyLine/data/questions/al_question_test.yml
- docassemble/AssemblyLine/data/questions/ql_baseline.yml
> Improve handling of contact methods

- docassemble/AssemblyLine/al_general.py
- docassemble/AssemblyLine/data/questions/al_question_test.yml
- docassemble/AssemblyLine/data/questions/al_settings.yml
- docassemble/AssemblyLine/data/questions/ql_baseline.yml
You could uncomment line 6 in al_question_test.yml to experiment with Canada/Canadian provinces
> Remove default state of "MA" and make it easier to set state/country as defaults on a package-wide basis

- docassemble/AssemblyLine/data/static/aldocument.css
- docassemble/AssemblyLine/data/static/styles.css
Removed outdated comments (over time some of the rules have changed but the comments stayed),
> Fix issue #186

- docassemble/AssemblyLine/al_document.py
- docassemble/AssemblyLine/data/questions/al_question_test.yml
Fix #195, but not yet #222
Also moved the download screen to the end to make it a little easier to find and change in the future.
> Respects the filename provided by the user in downloads

- docassemble/AssemblyLine/data/questions/ql_baseline.yml
> Fix #144 -- allow more interviews to run out of box in ALWeaver

- docassemble/AssemblyLine/al_document.py
Which hadn't been updated in the last big refactor.
Also wrapped a bunch of lines, because they were impossible to read without auto-line wrapping.
> Updated the download_html function

- .env_example
- .github/workflows/run_form_tests.yml
- .gitignore
- docassemble/AssemblyLine/data/sources/example_test.feature
- package.json
Updates:
[Set the secrets wrong. All should be good now. Note to self: workflow file should be added last.]
> Update to automated tests

- docassemble/AssemblyLine/data/questions/test_alexhibit.yml
Is this clarification what you're looking for? If not, it might be useful if you could add a suggestion or just edits to either this or to the original.
Also, thanks for catching my miss on the custom arguments!
> Implement custom class args. Visibly list what custom arguments are being tested on each page specifically.

- .gitignore
- docassemble/AssemblyLine/al_document.py
Addresses at least part of #263 from 1 day of testing. hard to tell if it totally solves it since the problem is intermittent
> Remove class attribute type annotations

- docassemble/AssemblyLine/al_general.py
See https://github.com/SuffolkLITLab/docassemble-EFSPIntegration/issues/45
quick test interview:
```yaml
---
include:
- al_package.yml
---
question: |
Test
fields:
- code: |
users[0].name_fields()
- code: |
users[1].name_fields(show_suffix=False)
```
> Make suffix an optional field to fit use in Tyler e-filing system

- docassemble/AssemblyLine/data/questions/ql_baseline.yml
> fix #257 Default birthdate questions to use datatype: BirthDate

- package.json
> Close #349, update to v3 of ALKiln auto testing

- .gitignore
- docassemble/AssemblyLine/al_courts.py
- docassemble/AssemblyLine/al_document.py
Unused so far, but UntransformedDocument was declared as a function
Some old changes that I had found with pylint but had never committed.
> Corrected a variable name, and ALUntransformedDocument is a class

- LICENSE
- docassemble/AssemblyLine/data/questions/ql_baseline.yml
> Close #286, fix use of ordinal for other users' names question

- package.json
See https://github.com/SuffolkLITLab/ALKiln/issues/489.
> For kiln tests, pin version of `colors` package

- docassemble/AssemblyLine/data/questions/ql_baseline.yml
> Add a generic object question for `x.fax_number`

- docassemble/AssemblyLine/al_document.py
> Close #403, remove unused table_css function

- docassemble/AssemblyLine/data/questions/ql_baseline.yml
> Fix #410 - incorrect label for "fax number"

- docassemble/AssemblyLine/al_general.py
- docassemble/AssemblyLine/data/questions/ql_baseline.yml
Fix #272 
Test interview:
```yaml
---
include:
---
question: |
You speak ${ users[0].language_name() }
```
> Add a language_fields() method to ALIndividual

- docassemble/AssemblyLine/al_document.py
- docassemble/AssemblyLine/data/questions/ql_baseline.yml
Fixes #316, is generally more accessible and consistent. See that issue for more discussion.
> Changes all `yesno` at top level to `yesnoradio`

- docassemble/AssemblyLine/data/questions/al_visual.yml
Fix #488, make the new answer set feature opt-in
> Create a feature flag for the Answer Set feature

- docassemble/AssemblyLine/data/questions/ql_baseline.yml
Fix #482
Can be overridden in Weaver still.
> Slightly nicer question and default for decedent in probate matters

- docassemble/AssemblyLine/data/questions/ql_baseline.yml
Prevents the too general "What is Bob Miller's Birthdate" from being asked by default.
> Add question for your birthdate

- docassemble/AssemblyLine/al_general.py
Sample interview:
```
---
include:
---
code: |
users[0].phone_number
---
question: |
subquestion: |
${ users[0].phone_numbers() }
${ phone_number_formatted(users[0].mobile_number, country=None) }
```
> Format user-entered phone numbers in `phone_numbers()` method

- docassemble/AssemblyLine/al_general.py
- docassemble/AssemblyLine/data/questions/ql_baseline.yml
Fix #597, fix #413 
At some point, this should link up with #581 (although note that  https://github.com/IllinoisLegalAidOnline/docassemble-Appearance/blob/main/docassemble/Appearance/data/questions/appearance.yml uses the word "lawyer" instead of "attorney" which might be better.
> Add simple service of process questions

- docassemble/AssemblyLine/al_courts.py
Most states have one court per county, except in the largest population counties. This adds to the ALCourtLoader API to make it very easy to figure out if the given county has multiple courts and adds a simple method of asking a follow-up question about the specific court the user wants to file in from among the list of courts in the given county.
I've also added a method that allows doing simple keyword searches against an arbitrary column to further filter the results. This is because in the very largest county, there are often specialty courts with limited jurisdiction--such as a family court, juvenile court, etc.
New methods:
* county_list - list all of the unique county names in the spreadsheet
* county_has_one_court(county) - true/false if the county has more than one court
* …
> Better API for searching courts by county

- docassemble/AssemblyLine/al_general.py
- docassemble/AssemblyLine/language.py
- docassemble/AssemblyLine/sessions.py
See https://github.com/SuffolkLITLab/docassemble-AssemblyLine/issues/658 for full details.
Let me know if I missed anything here, I tested `interview_list` as much as I could on 1.4.36 and 1.4.32.
> Update to SQL Alchemy 2.0

- docassemble/AssemblyLine/data/questions/al_code.yml
- docassemble/AssemblyLine/data/questions/al_visual.yml
> Improve safety + content of about, download work in progress, and custom error action pages

- docassemble/AssemblyLine/data/questions/al_saved_sessions.yml
> Default to updating metadata on every screen load, not every third

- .gitignore
- docassemble/AssemblyLine/sessions.py
Changes that I needed to make when testing a local version of Interview assembly, which turned out not to work, but I think are still useful.
Will do a quick check on a server with sessions stuff, I'll merge if it works.
> Removed unused imports from sessions.py

- docassemble/AssemblyLine/al_general.py
- docassemble/AssemblyLine/data/questions/ql_baseline.yml
1. Translatable contact method fields, fix #216 
2. Add a new, optional "title" parameter when using name fields. Fix #208
> Minor enhancements to contact fields, name field

- docassemble/AssemblyLine/al_general.py
- docassemble/AssemblyLine/test_al_general.py
Always show the user given phone number if the formatted number is None.
Adds tests for this specific issue. Will merge when said tests pass.
> More safety around phone numbers

- docassemble/AssemblyLine/al_courts.py
- docassemble/AssemblyLine/language.py
- docassemble/AssemblyLine/sessions.py
> Make it possible to hide certain icons related to answer sets on view sessions page

- docassemble/AssemblyLine/al_document.py
- docassemble/AssemblyLine/al_general.py
@mnewsted I'm opening this up as a draft PR for now, LMK if the API makes sense.
> Add an optional `maxlength` attribute to any `_fields` methods

- .github/workflows/run_form_tests.yml
https://assemblyline.suffolklitlab.org/docs/components/ALKiln/setup/#sandbox-how-to
> Implement ALKiln GitHub Sandbox tests

- docassemble/AssemblyLine/data/questions/al_code.yml
- docassemble/AssemblyLine/data/questions/al_saved_sessions.yml
- docassemble/AssemblyLine/data/questions/al_saved_sessions_store.yml
- docassemble/AssemblyLine/data/questions/al_settings.yml
- docassemble/AssemblyLine/data/questions/al_visual.yml
- docassemble/AssemblyLine/data/questions/interview_list.yml
- docassemble/AssemblyLine/sessions.py
Fix #913 Fix #820
The purpose of this PR is to help troubleshoot errors that the user isn't good at explaining! I'll open up another PR in the "View Answer files" dashboard that lets us comfortably lookup a case by session ID without needing to construct the full URL manually.
> Add session ID to HUD

- .github/workflows/publish.yml
- docassemble/AssemblyLine/al_general.py
Also merge leftover Black formatting
> Upgrade github workflow runner
